### PR TITLE
Do not thow exception if zipkin is down at start up

### PR DESCRIPTION
**Pull request by pavolloffay**
I think this should not stop the application if zipkin is not running.

### CODE REVIEW

**Comment by pavolloffay** [comment]
@jplock could you please review?

**Comment by jplock** [comment]
Thanks!  I wasn't sure if people would want the service to fail on startup if it can't communicate to zipkin, but I guess it will keep trying on each request being sampled so this should be ok.  I won't be able to publish an updated version to Maven Central until at least tomorrow.

**Comment by pavolloffay** [comment]
@jplock thanks!

**Comment by jplock** [comment]
I just pushed 1.0.5-3 to Maven Central

**Pull request merged**
