### PR TITLE
set entire sampler instead of just sample rate

### PR DESCRIPTION
**Pull request by spudone**
See:
https://github.com/smoketurner/dropwizard-zipkin/issues/13

### CODE REVIEW

**Comment by jplock** [comment]
With this change there's really no way to pass in a sampling rate via the configuration file.  I think modifying the getter/setters are ok, but I'd like to provide a sane sampler default implementation and still allow configuring the sample rate via the config file.

**Comment by spudone** [comment]
Any sampler passed in requires a sampling rate, so it is still provided, just one layer deeper.  Maybe this could be handled in getSampler by returning a default if one hasn't been set.  That said, I think CountingSampler is a poor default as it will absolutely fall over under any kind of load.

**Comment by adriancole** [comment]
agree with most things except poor default. boundary sampling is absolutely
a poor default and that was proven out with practice. Try describing to a
new user why none of their traces pass sample :) The response of.. oh just
generate a few thousand requests, you'll see! << not that productive.

In other words, please don't change the default as that puts support burden
on new users. Similar to how it is described in Brave, the boundary sampler
is for high load sites and also assumes good trace id coverage (which
currently isn't great as Random.getLong is only 48bit)

**Comment by spudone** [comment]
I don't have a problem with a higher default sample rate.  The issue I have is that a) CountingSampler can't drop below 1%, and b) it is the default in dropwizard-zipkin and can't currently be changed.

I'll make some changes to my pull request to leave a default in place, but the sampler should be user-configurable, as an option.

**Comment by spudone** [comment]
Feels a bit ugly, but this should be less intrusive - the default is now the same as before, while users have the option to create the sampler directly.

**Comment by adriancole** [comment]
right, if the sampler impl was injectable you could paste a variant that
simply updates the magnitude of the counting sampler. Ex. if your copy had
a magnitude of 1000, it would allow you to specify partial fraction at the
cost of lower feedback (ex you wouldn't be guaranteed to see a trace until
that count happened). Also, a custom sampler impl could allow for a dynamic
rate.

**Pull request merged**
